In [64]:
import numpy as np
import tensorflow as tf

# training data

x_train = np.random.randn(1,5)
y_train = [[0.3]]
#y_train = np.random.randn(0,1)


input_num_units = 5
hidden_num_units = 3
output_num_units = 1

# define placeholders

x = tf.placeholder(tf.float32, [None, input_num_units])
y = tf.placeholder(tf.float32)
 

# define computational graph
# Create the model

W_in = tf.Variable(tf.zeros([input_num_units, hidden_num_units]))
b_in = tf.Variable(tf.zeros([hidden_num_units]))
x_out = tf.matmul(x, W_in) + b_in
h_in = tf.nn.relu(x_out)
W_out = tf.Variable(tf.zeros([hidden_num_units, output_num_units]))
b_out = tf.Variable(tf.zeros([output_num_units]))
h_out = tf.matmul(h_in, W_out) + b_out
y_out= tf.nn.sigmoid(h_out) 


#initializer
init = tf.global_variables_initializer()


# loss
#loss = tf.nn.l2_loss(y_out - y_train) # sum of the squares
loss = abs(y_out - y_train)


# optimizer
optimizer = tf.train.GradientDescentOptimizer(0.01)# 0.01 is learning rate
train = optimizer.minimize(loss)


#initializer
init = tf.global_variables_initializer()

#run the graph as session


with tf.Session() as sess:
    sess.run(init) # reset values to wrong
    # training loop
    for i in range(500):
        sess.run(train, {x:x_train, y:y_train})
                

    # evaluate training accuracy
    #curr_W, curr_b, curr_loss = sess.run([W, b, loss], {x_in:x_train, y_out:y_train})
    #print("W: %s b: %s loss: %s"%(curr_W, curr_b, curr_loss))
    
    curr_W_in, curr_b_in = sess.run([W_in, b_in], {x:x_train, y:y_train})
    print("W_in: %s b_in: %s"%(curr_W_in, curr_b_in))
    
    curr_W_out, curr_b_out = sess.run([W_out, b_out], {x:x_train, y:y_train})
    print("W_out: %s b_out: %s"%(curr_W_out, curr_b_out))
    x = sess.run((y_out), {x:x_train, y:y_train})
    print("Value of y:",x)

W_in: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] b_in: [0. 0. 0.]
W_out: [[0.]
 [0.]
 [0.]] b_out: [-0.8477392]
Value of y: [[0.29990733]]
